# Generated by Django 4.1 on 2022-10-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dadosusuario", old_name="usuario", new_name="Nome",
        ),
    ]
