# Generated by Django 4.1.2 on 2022-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="dataNascimento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nomeMae",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="prontuario",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
