# Generated by Django 4.1 on 2022-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0002_rename_usuario_dadosusuario_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacienteCirurgia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("dataNascimento", models.DateField()),
                ("nomeMae", models.CharField(max_length=50)),
                ("prontuario", models.CharField(max_length=15)),
                ("cirurgiaProposta", models.CharField(max_length=50)),
                ("cirurgiaRealizada", models.CharField(max_length=50)),
                ("salaCirugica", models.CharField(max_length=50)),
                ("dataCirurugia", models.DateField(max_length=10)),
                ("modalidade", models.CharField(max_length=1)),
                ("realizouQuimeoterapia", models.CharField(max_length=1)),
                ("quantasSQ", models.IntegerField()),
                ("realizouRadioterapia", models.CharField(max_length=1)),
                ("quantasRR", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="DadosUsuario",),
    ]
